Calculated Policy - AWS EC2 Instance Approved based on Image tags #504
turbot/tdk pull request #505
Opened 2021-03-17 22:14 UTC by choxie

closes #504

2021-03-18 08:49 UTC, omerosaienni requested changes

2021-03-18 08:49 UTC, omerosaienni commented on calculated_policies/aws_ec2_approved_image_tag/main.tf
> +resource "turbot_smart_folder" "aws_ec2_folder" {
This can live in the file smart_folder.tf

2021-03-18 08:49 UTC, omerosaienni commented on calculated_policies/aws_ec2_approved_image_tag/main.tf
> +terraform {
This lives in the file providers.tf

2021-03-18 08:49 UTC, omerosaienni commented on calculated_policies/aws_ec2_approved_image_tag/variables.tf
> +variable "smart_folder_title" {
Variables now have a file called output.tf that displays their values. 

These values are then sent back to the end user at the end of the apply for their reference.

2021-03-18 08:49 UTC, omerosaienni commented on calculated_policies/aws_ec2_approved_image_tag/variables.tf
> +variable "smart_folder_title" {
To clarify, variables are defined here.

The values of the variables are defined in `output.tf`

2021-03-18 16:32 UTC, vkumbha commented
Please ignore this comment! Testing slack!

2021-03-19 10:38 UTC, omerosaienni requested changes

2021-03-19 10:38 UTC, omerosaienni commented on calculated_policies/aws_ec2_approved_image_tag/variables.tf
> +
Add this

```terraform
variable "turbot_profile" {
  description = "Enter profile matching your turbot cli credentials."
}
```

2021-03-19 10:38 UTC, omerosaienni commented on calculated_policies/aws_ec2_approved_image_tag/providers.tf
> +terraform {
Add this

```terraform
provider "turbot" {
  profile = var.turbot_profile
}
```

2021-03-24 11:20 UTC, omerosaienni approved these changes

2021-03-24 11:21 UTC, merged